### ISSUE TITLE
If I use youtube as focus, it gives other sources too 🥺 

### ISSUE THREAD

**Issue by CutyCat2000** [helallao/perplexity-ai#19]
If I use youtube as focus, it gives other sources too 🥺

**Comment by helallao** [comment]
It seems there are no other sources else youtube. Surely it may be because of your query, if you find a query which has other sources, you can publish the query here. Maybe you're using wrong list/dictionary in response json. Sources dictionary is at ``['text']['web_results']`` in response. Like this:

```python
print(perplexity_cli.search('Your query here', mode='concise', focus='youtube', solvers={
        'text': my_text_prompt_solver,
        'checkbox': my_checkbox_prompt_solver
    })['text']['web_results'])
```
![image](https://github.com/helallao/perplexity-ai/assets/78656003/2105c62b-b805-4de3-aa81-9669ea19355e)
