### ISSUE TITLE
ModuleNotFoundError: No module named 'perplexity'

### ISSUE THREAD

**Issue by xts-bit** [helallao/perplexity-ai#30]
Hi, I'm getting this error while running my script ModuleNotFoundError: No module named 'perplexity' Can anyone help me with this? I used the code example in the readme file and followed every step of it, i ran this command "pip3 install requests&&pip3 install beautifulsoup4&&pip3 install lxml&&pip3 install websocket-client&&pip3 install requests-toolbelt"

and pip3 install perplexity is just not working

**Comment by helallao** [comment]
yes because there is no library named as perplexity in [pypi](https://pypi.org/), i did not added it to pypi because it's just single-file python module. Just install the other libraries and use [perplexity.py](https://github.com/helallao/perplexity-ai/blob/main/perplexity.py) or [perplexity_async.py](https://github.com/helallao/perplexity-ai/blob/main/perplexity_async.py) which can be found in files section.

**Comment by xts-bit** [comment]
@helallao  i get this error now Error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

**Comment by helallao** [comment]
It doesn't happen to me. Shut off if you're using a vpn or something intersecting to your network. There may be some outdated libraries, run this command to force all libraries to update:

```
pip3 install -U requests&&pip3 install -U beautifulsoup4&&pip3 install -U lxml&&pip3 install -U websocket-client&&pip3 install -U requests-toolbelt
```

**Comment by berthin** [comment]
> [@helallao](https://github.com/helallao) i get this error now Error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

Hey, I got the same issue on Mac and this helped: https://stackoverflow.com/a/62374703

```bash
$ open /Applications/Python\ 3.6/Install\ Certificates.command
```
